### ISSUE TITLE
Playthrough Notes

### ISSUE THREAD

**Issue by gap9269** [gap9269/SDD#1681]

**Comment by gap9269** [comment]
- Road's End, when entering from Lost Hall, the platform extends all the way to the left until you jump. Does this happen in all maps?

**Comment by gap9269** [comment]
- Add bathroom after kents death

**Comment by dpp5221** [comment]
- extend foreground in library map before Eli's office
- demon paul and alan could use better dialogue post minotaur death
- Genghis' dialogue is placeholder in gem gathering quest

**Comment by gap9269** [comment]
- Backwards science 101 missing treasure room on map
- Genghis slay quest isnt working for troll kills (maybe it is, but old saves aren't. make sure enemy names are correct and if not, fix them)
- napoleon map updates cover up daryl icon
- no bathroom icon for mongolian camp map

**Comment by gap9269** [comment]
- Flowers for wobbles quest still bugged? (Quest tasks overlap)
- Janitor face in Axis 2 is wrong if you're playing nonstop?
- Take it back doesn't have skill info in skill menu
- Hit level 45, can't open up in-game menu or it crashes

**Comment by gap9269** [comment]
- Lots of desert glitch area crashes

**Comment by gap9269** [comment]
- Talking to backwards science TK in late CH4 causes crash
- Players with older saves will crash due to Einstein maybe?

Source        : MonoGame.Framework
Method        : OpenStream
Date        : 12:14:42 AM
Time        : 1/31/2018
Error        : The content file was not found.
Stack Trace    : at Microsoft.Xna.Framework.Content.ContentManager.OpenStream(String assetName)
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
   at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName)
   at ISurvived.BioPage.LoadEnemyOrNPCPictures()
   at ISurvived.BioPage.Draw(SpriteBatch s)
   at ISurvived.DarylsNotebook.Draw(SpriteBatch s)
   at ISurvived.Chapter.DrawStaticStuff(SpriteBatch s, Camera camera)
   at ISurvived.Chapter.Draw(SpriteBatch s, Camera camera)
   at ISurvived.ChapterFour.Draw(SpriteBatch s, Camera camera)
   at ISurvived.Game1.DrawCode(GameTime gameTime)
   at ISurvived.Game1.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at ISurvived.Program.Main(String[] args)
^^-------------------------------------------------------------------^^
